// src/app/docs/[slug]/page.tsx
import { notFound } from 'next/navigation'
import EssentialLink from '@/app/ui/essential-link'
import { parseMarkdown } from "@/lib/md-convert"
import { queryCollectionNavigation, queryCollection } from '@/lib/api'



export default async function Page({ params }: { params: Promise<{ slug: string }> }) {
  const navigation = await queryCollectionNavigation('docs')

  const slug = (await params).slug
  const data = await queryCollection('docs').path(slug)

  if (!data) {
    return notFound()
  }

  const content = await parseMarkdown(data.content || "")
  return (
    <div className='flex space-x-24'>
      <EssentialLink items={navigation} />
      <article className="flex min-h-screen flex-col items-center justify-center overflow-hidden py-8 md:pb-16">
        <div className="w-full grow rounded-sm md:shadow-lg dark:shadow-lime-700/40 max-w-4xl 2xl:max-w-6xl p-4 md:py-16">
          <div
            className='mx-auto prose 2xl:prose-xl prose-a:text-lime-600 dark:prose-invert dark:prose-pre:bg-gray-800'
            dangerouslySetInnerHTML={{ __html: content }}
          />
        </div>
      </article>
    </div>
  )
}

// app/pages/blogs/[...slug].vue
<script setup lang="ts">
const route = useRoute()
const { data: navigation } = await useAsyncData(() => queryCollectionNavigation('blogs'))

const { data: page } = await useAsyncData(route.path, () => queryCollection('blogs').path(route.path).first())
if (!page.value) {
  throw createError({ statusCode: 404, statusMessage: 'Page not found', fatal: true })
}
</script>

<template>
  <section class="flex space-x-12 p-6">
    <div class="hidden h-full max-h-screen w-64 shrink-0 overflow-auto rounded-sm bg-gray-50 lg:block">
      <EssentialLink :items="navigation" />
    </div>

    <div class="flex h-full flex-1 flex-col items-center overflow-hidden lg:pb-16">
      <h1 className="text-2xl mx-auto max-w-2xl font-semibold tracking-tight text-center lg:text-4xl">
        {{ page?.title }}
      </h1>
      <div class="w-full grow rounded-sm md:shadow-lg dark:shadow-lime-700/40 max-w-5xl md:py-16">
        <ContentRenderer v-if="page" :value="page"
          class="prose ma-auto max-w-3xl dark:prose-invert prose-pre:bg-gray-100 dark:prose-pre:bg-gray-900 mx-auto" />
      </div>
    </div>
  </section>
</template>
