// app/pages/docs/index.vue
<script setup lang="ts">
const { data: navigation } = await useAsyncData(() => queryCollectionNavigation('docs'))

const { data: page } = await useAsyncData(() => queryCollection('docs').first())
if (!page.value) {
  throw createError({ statusCode: 404, statusMessage: 'Page not found', fatal: true })
}
</script>

<template>
  <section class="flex space-x-12 p-6">
    <div class="hidden h-full max-h-screen w-64 shrink-0 overflow-auto rounded-sm bg-gray-50 lg:block">
      <EssentialLink :items="navigation" />
    </div>

    <div class="inline-flex flex-1 h-full flex-col items-center overflow-hidden lg:pb-16">
      <div class="w-full grow rounded-md md:shadow-lg dark:shadow-lime-700/40 max-w-5xl md:py-16">
        <ContentRenderer v-if="page" :value="page"
          class="prose ma-auto max-w-3xl dark:prose-invert prose-pre:bg-gray-100 dark:prose-pre:bg-gray-900 mx-auto" />
      </div>
    </div>
  </section>
</template>

// src/app/docs/page.tsx
import EssentialLink from '@/app/ui/essential-link'
import { parseMarkdown } from "@/lib/md-convert"
import { queryCollectionNavigation, queryCollection } from '@/lib/api'

export default async function Page() {
  const navigation = await queryCollectionNavigation('docs')

  const data = await queryCollection('docs').first()
  if (!data) {
    throw new Error("No documents found");
  }

  const content = await parseMarkdown(data.content || "")
  return (
    <div className='flex space-x-24'>
      <EssentialLink items={navigation} />
      <article className="flex min-h-screen flex-col items-center justify-center overflow-hidden py-8 md:py-16">
        <div className="w-full grow rounded-sm md:shadow-lg dark:shadow-lime-700/40 max-w-4xl 2xl:max-w-7xl p-4 md:py-16">
          <div
            className='mx-auto prose 2xl:prose-xl prose-a:text-lime-600 dark:prose-invert dark:prose-pre:bg-gray-800'
            dangerouslySetInnerHTML={{ __html: content }}
          />
        </div>
      </article>
    </div>
  )
}
